//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
        "ceManagementV1")]
    public partial class GenericFault
    {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors
        {
            get
            {
                return this.wrappedErrorsField;
            }
            set
            {
                this.wrappedErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
        "ceManagementV1")]
    public partial class GenericFaultParameter
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
        "ceManagementV1")]
    public partial class WrappedError
    {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
        "ceManagementV1")]
    public partial class CatalogDataProductTierPriceExtensionInterface
    {
        
        private float percentageValueField;
        
        private bool percentageValueFieldSpecified;
        
        private int websiteIdField;
        
        private bool websiteIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public float percentageValue
        {
            get
            {
                return this.percentageValueField;
            }
            set
            {
                this.percentageValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool percentageValueSpecified
        {
            get
            {
                return this.percentageValueFieldSpecified;
            }
            set
            {
                this.percentageValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int websiteId
        {
            get
            {
                return this.websiteIdField;
            }
            set
            {
                this.websiteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool websiteIdSpecified
        {
            get
            {
                return this.websiteIdFieldSpecified;
            }
            set
            {
                this.websiteIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
        "ceManagementV1")]
    public partial class CatalogDataProductTierPriceInterface
    {
        
        private int customerGroupIdField;
        
        private float qtyField;
        
        private float valueField;
        
        private CatalogDataProductTierPriceExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int customerGroupId
        {
            get
            {
                return this.customerGroupIdField;
            }
            set
            {
                this.customerGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public float qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public float value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public CatalogDataProductTierPriceExtensionInterface extensionAttributes
        {
            get
            {
                return this.extensionAttributesField;
            }
            set
            {
                this.extensionAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
        "ceManagementV1")]
    public partial class CatalogProductTierPriceManagementV1GetListResponse
    {
        
        private CatalogDataProductTierPriceInterface[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CatalogDataProductTierPriceInterface[] result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
        "ceManagementV1")]
    public partial class CatalogProductTierPriceManagementV1GetListRequest
    {
        
        private string skuField;
        
        private string customerGroupIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sku
        {
            get
            {
                return this.skuField;
            }
            set
            {
                this.skuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string customerGroupId
        {
            get
            {
                return this.customerGroupIdField;
            }
            set
            {
                this.customerGroupIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
        "ceManagementV1", ConfigurationName="Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTie" +
        "rPriceManagementV1.catalogProductTierPriceManagementV1PortType")]
    public interface catalogProductTierPriceManagementV1PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductTierPriceManagementV1GetList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.GenericFault), Action="catalogProductTierPriceManagementV1GetList", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1GetListResponse1> catalogProductTierPriceManagementV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1GetListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductTierPriceManagementV1Add", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.GenericFault), Action="catalogProductTierPriceManagementV1Add", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1AddResponse1> catalogProductTierPriceManagementV1AddAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1AddRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductTierPriceManagementV1Remove", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.GenericFault), Action="catalogProductTierPriceManagementV1Remove", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1RemoveResponse1> catalogProductTierPriceManagementV1RemoveAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1RemoveRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductTierPriceManagementV1GetListRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
            "ceManagementV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1GetListRequest catalogProductTierPriceManagementV1GetListRequest;
        
        public catalogProductTierPriceManagementV1GetListRequest1()
        {
        }
        
        public catalogProductTierPriceManagementV1GetListRequest1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1GetListRequest catalogProductTierPriceManagementV1GetListRequest)
        {
            this.catalogProductTierPriceManagementV1GetListRequest = catalogProductTierPriceManagementV1GetListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductTierPriceManagementV1GetListResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
            "ceManagementV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1GetListResponse catalogProductTierPriceManagementV1GetListResponse;
        
        public catalogProductTierPriceManagementV1GetListResponse1()
        {
        }
        
        public catalogProductTierPriceManagementV1GetListResponse1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1GetListResponse catalogProductTierPriceManagementV1GetListResponse)
        {
            this.catalogProductTierPriceManagementV1GetListResponse = catalogProductTierPriceManagementV1GetListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
        "ceManagementV1")]
    public partial class CatalogProductTierPriceManagementV1AddRequest
    {
        
        private string skuField;
        
        private string customerGroupIdField;
        
        private float priceField;
        
        private float qtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sku
        {
            get
            {
                return this.skuField;
            }
            set
            {
                this.skuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string customerGroupId
        {
            get
            {
                return this.customerGroupIdField;
            }
            set
            {
                this.customerGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public float price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public float qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
        "ceManagementV1")]
    public partial class CatalogProductTierPriceManagementV1AddResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductTierPriceManagementV1AddRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
            "ceManagementV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1AddRequest catalogProductTierPriceManagementV1AddRequest;
        
        public catalogProductTierPriceManagementV1AddRequest1()
        {
        }
        
        public catalogProductTierPriceManagementV1AddRequest1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1AddRequest catalogProductTierPriceManagementV1AddRequest)
        {
            this.catalogProductTierPriceManagementV1AddRequest = catalogProductTierPriceManagementV1AddRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductTierPriceManagementV1AddResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
            "ceManagementV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1AddResponse catalogProductTierPriceManagementV1AddResponse;
        
        public catalogProductTierPriceManagementV1AddResponse1()
        {
        }
        
        public catalogProductTierPriceManagementV1AddResponse1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1AddResponse catalogProductTierPriceManagementV1AddResponse)
        {
            this.catalogProductTierPriceManagementV1AddResponse = catalogProductTierPriceManagementV1AddResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
        "ceManagementV1")]
    public partial class CatalogProductTierPriceManagementV1RemoveRequest
    {
        
        private string skuField;
        
        private string customerGroupIdField;
        
        private float qtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sku
        {
            get
            {
                return this.skuField;
            }
            set
            {
                this.skuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string customerGroupId
        {
            get
            {
                return this.customerGroupIdField;
            }
            set
            {
                this.customerGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public float qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
        "ceManagementV1")]
    public partial class CatalogProductTierPriceManagementV1RemoveResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductTierPriceManagementV1RemoveRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
            "ceManagementV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1RemoveRequest catalogProductTierPriceManagementV1RemoveRequest;
        
        public catalogProductTierPriceManagementV1RemoveRequest1()
        {
        }
        
        public catalogProductTierPriceManagementV1RemoveRequest1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1RemoveRequest catalogProductTierPriceManagementV1RemoveRequest)
        {
            this.catalogProductTierPriceManagementV1RemoveRequest = catalogProductTierPriceManagementV1RemoveRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductTierPriceManagementV1RemoveResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
            "ceManagementV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1RemoveResponse catalogProductTierPriceManagementV1RemoveResponse;
        
        public catalogProductTierPriceManagementV1RemoveResponse1()
        {
        }
        
        public catalogProductTierPriceManagementV1RemoveResponse1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1RemoveResponse catalogProductTierPriceManagementV1RemoveResponse)
        {
            this.catalogProductTierPriceManagementV1RemoveResponse = catalogProductTierPriceManagementV1RemoveResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public interface catalogProductTierPriceManagementV1PortTypeChannel : Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public partial class catalogProductTierPriceManagementV1PortTypeClient : System.ServiceModel.ClientBase<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1PortType>, Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1PortType
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public catalogProductTierPriceManagementV1PortTypeClient() : 
                base(catalogProductTierPriceManagementV1PortTypeClient.GetDefaultBinding(), catalogProductTierPriceManagementV1PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.catalogProductTierPriceManagementV1Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public catalogProductTierPriceManagementV1PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(catalogProductTierPriceManagementV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), catalogProductTierPriceManagementV1PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public catalogProductTierPriceManagementV1PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(catalogProductTierPriceManagementV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public catalogProductTierPriceManagementV1PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(catalogProductTierPriceManagementV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public catalogProductTierPriceManagementV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1GetListResponse1> Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1PortType.catalogProductTierPriceManagementV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1GetListRequest1 request)
        {
            return base.Channel.catalogProductTierPriceManagementV1GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1GetListResponse1> catalogProductTierPriceManagementV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1GetListRequest catalogProductTierPriceManagementV1GetListRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1GetListRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1GetListRequest1();
            inValue.catalogProductTierPriceManagementV1GetListRequest = catalogProductTierPriceManagementV1GetListRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1PortType)(this)).catalogProductTierPriceManagementV1GetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1AddResponse1> Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1PortType.catalogProductTierPriceManagementV1AddAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1AddRequest1 request)
        {
            return base.Channel.catalogProductTierPriceManagementV1AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1AddResponse1> catalogProductTierPriceManagementV1AddAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1AddRequest catalogProductTierPriceManagementV1AddRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1AddRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1AddRequest1();
            inValue.catalogProductTierPriceManagementV1AddRequest = catalogProductTierPriceManagementV1AddRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1PortType)(this)).catalogProductTierPriceManagementV1AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1RemoveResponse1> Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1PortType.catalogProductTierPriceManagementV1RemoveAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1RemoveRequest1 request)
        {
            return base.Channel.catalogProductTierPriceManagementV1RemoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1RemoveResponse1> catalogProductTierPriceManagementV1RemoveAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.CatalogProductTierPriceManagementV1RemoveRequest catalogProductTierPriceManagementV1RemoveRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1RemoveRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1RemoveRequest1();
            inValue.catalogProductTierPriceManagementV1RemoveRequest = catalogProductTierPriceManagementV1RemoveRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CatalogProductTierPriceManagementV1.catalogProductTierPriceManagementV1PortType)(this)).catalogProductTierPriceManagementV1RemoveAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.catalogProductTierPriceManagementV1Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.catalogProductTierPriceManagementV1Port))
            {
                return new System.ServiceModel.EndpointAddress("http://connector.monnier.cidev04.test/soap/default?services=catalogProductTierPri" +
                        "ceManagementV1");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return catalogProductTierPriceManagementV1PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.catalogProductTierPriceManagementV1Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return catalogProductTierPriceManagementV1PortTypeClient.GetEndpointAddress(EndpointConfiguration.catalogProductTierPriceManagementV1Port);
        }
        
        public enum EndpointConfiguration
        {
            
            catalogProductTierPriceManagementV1Port,
        }
    }
}
