//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
        "ntV1")]
    public partial class GenericFault
    {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors
        {
            get
            {
                return this.wrappedErrorsField;
            }
            set
            {
                this.wrappedErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
        "ntV1")]
    public partial class GenericFaultParameter
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
        "ntV1")]
    public partial class WrappedError
    {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
        "ntV1")]
    public partial class CustomerDataGroupExtensionInterface
    {
        
        private int[] excludeWebsiteIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public int[] excludeWebsiteIds
        {
            get
            {
                return this.excludeWebsiteIdsField;
            }
            set
            {
                this.excludeWebsiteIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
        "ntV1")]
    public partial class CustomerDataGroupInterface
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string codeField;
        
        private int taxClassIdField;
        
        private string taxClassNameField;
        
        private CustomerDataGroupExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int taxClassId
        {
            get
            {
                return this.taxClassIdField;
            }
            set
            {
                this.taxClassIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string taxClassName
        {
            get
            {
                return this.taxClassNameField;
            }
            set
            {
                this.taxClassNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public CustomerDataGroupExtensionInterface extensionAttributes
        {
            get
            {
                return this.extensionAttributesField;
            }
            set
            {
                this.extensionAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
        "ntV1")]
    public partial class CustomerGroupManagementV1GetDefaultGroupResponse
    {
        
        private CustomerDataGroupInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CustomerDataGroupInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
        "ntV1")]
    public partial class CustomerGroupManagementV1GetDefaultGroupRequest
    {
        
        private int storeIdField;
        
        private bool storeIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int storeId
        {
            get
            {
                return this.storeIdField;
            }
            set
            {
                this.storeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool storeIdSpecified
        {
            get
            {
                return this.storeIdFieldSpecified;
            }
            set
            {
                this.storeIdFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
        "ntV1", ConfigurationName="Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupMana" +
        "gementV1.customerGroupManagementV1PortType")]
    public interface customerGroupManagementV1PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupManagementV1GetDefaultGroup", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.GenericFault), Action="customerGroupManagementV1GetDefaultGroup", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1GetDefaultGroupResponse1> customerGroupManagementV1GetDefaultGroupAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1GetDefaultGroupRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupManagementV1IsReadonly", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.GenericFault), Action="customerGroupManagementV1IsReadonly", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1IsReadonlyResponse1> customerGroupManagementV1IsReadonlyAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1IsReadonlyRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupManagementV1GetDefaultGroupRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
            "ntV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.CustomerGroupManagementV1GetDefaultGroupRequest customerGroupManagementV1GetDefaultGroupRequest;
        
        public customerGroupManagementV1GetDefaultGroupRequest1()
        {
        }
        
        public customerGroupManagementV1GetDefaultGroupRequest1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.CustomerGroupManagementV1GetDefaultGroupRequest customerGroupManagementV1GetDefaultGroupRequest)
        {
            this.customerGroupManagementV1GetDefaultGroupRequest = customerGroupManagementV1GetDefaultGroupRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupManagementV1GetDefaultGroupResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
            "ntV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.CustomerGroupManagementV1GetDefaultGroupResponse customerGroupManagementV1GetDefaultGroupResponse;
        
        public customerGroupManagementV1GetDefaultGroupResponse1()
        {
        }
        
        public customerGroupManagementV1GetDefaultGroupResponse1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.CustomerGroupManagementV1GetDefaultGroupResponse customerGroupManagementV1GetDefaultGroupResponse)
        {
            this.customerGroupManagementV1GetDefaultGroupResponse = customerGroupManagementV1GetDefaultGroupResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
        "ntV1")]
    public partial class CustomerGroupManagementV1IsReadonlyRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
        "ntV1")]
    public partial class CustomerGroupManagementV1IsReadonlyResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupManagementV1IsReadonlyRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
            "ntV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.CustomerGroupManagementV1IsReadonlyRequest customerGroupManagementV1IsReadonlyRequest;
        
        public customerGroupManagementV1IsReadonlyRequest1()
        {
        }
        
        public customerGroupManagementV1IsReadonlyRequest1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.CustomerGroupManagementV1IsReadonlyRequest customerGroupManagementV1IsReadonlyRequest)
        {
            this.customerGroupManagementV1IsReadonlyRequest = customerGroupManagementV1IsReadonlyRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupManagementV1IsReadonlyResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
            "ntV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.CustomerGroupManagementV1IsReadonlyResponse customerGroupManagementV1IsReadonlyResponse;
        
        public customerGroupManagementV1IsReadonlyResponse1()
        {
        }
        
        public customerGroupManagementV1IsReadonlyResponse1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.CustomerGroupManagementV1IsReadonlyResponse customerGroupManagementV1IsReadonlyResponse)
        {
            this.customerGroupManagementV1IsReadonlyResponse = customerGroupManagementV1IsReadonlyResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public interface customerGroupManagementV1PortTypeChannel : Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public partial class customerGroupManagementV1PortTypeClient : System.ServiceModel.ClientBase<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1PortType>, Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1PortType
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public customerGroupManagementV1PortTypeClient() : 
                base(customerGroupManagementV1PortTypeClient.GetDefaultBinding(), customerGroupManagementV1PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.customerGroupManagementV1Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public customerGroupManagementV1PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(customerGroupManagementV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), customerGroupManagementV1PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public customerGroupManagementV1PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(customerGroupManagementV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public customerGroupManagementV1PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(customerGroupManagementV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public customerGroupManagementV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1GetDefaultGroupResponse1> Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1PortType.customerGroupManagementV1GetDefaultGroupAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1GetDefaultGroupRequest1 request)
        {
            return base.Channel.customerGroupManagementV1GetDefaultGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1GetDefaultGroupResponse1> customerGroupManagementV1GetDefaultGroupAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.CustomerGroupManagementV1GetDefaultGroupRequest customerGroupManagementV1GetDefaultGroupRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1GetDefaultGroupRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1GetDefaultGroupRequest1();
            inValue.customerGroupManagementV1GetDefaultGroupRequest = customerGroupManagementV1GetDefaultGroupRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1PortType)(this)).customerGroupManagementV1GetDefaultGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1IsReadonlyResponse1> Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1PortType.customerGroupManagementV1IsReadonlyAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1IsReadonlyRequest1 request)
        {
            return base.Channel.customerGroupManagementV1IsReadonlyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1IsReadonlyResponse1> customerGroupManagementV1IsReadonlyAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.CustomerGroupManagementV1IsReadonlyRequest customerGroupManagementV1IsReadonlyRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1IsReadonlyRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1IsReadonlyRequest1();
            inValue.customerGroupManagementV1IsReadonlyRequest = customerGroupManagementV1IsReadonlyRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupManagementV1.customerGroupManagementV1PortType)(this)).customerGroupManagementV1IsReadonlyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.customerGroupManagementV1Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.customerGroupManagementV1Port))
            {
                return new System.ServiceModel.EndpointAddress("http://connector.monnier.cidev04.test/soap/default?services=customerGroupManageme" +
                        "ntV1");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return customerGroupManagementV1PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.customerGroupManagementV1Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return customerGroupManagementV1PortTypeClient.GetEndpointAddress(EndpointConfiguration.customerGroupManagementV1Port);
        }
        
        public enum EndpointConfiguration
        {
            
            customerGroupManagementV1Port,
        }
    }
}
