//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class GenericFault
    {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors
        {
            get
            {
                return this.wrappedErrorsField;
            }
            set
            {
                this.wrappedErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class GenericFaultParameter
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class WrappedError
    {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class CustomerDataGroupExtensionInterface
    {
        
        private int[] excludeWebsiteIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public int[] excludeWebsiteIds
        {
            get
            {
                return this.excludeWebsiteIdsField;
            }
            set
            {
                this.excludeWebsiteIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class CustomerDataGroupInterface
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string codeField;
        
        private int taxClassIdField;
        
        private string taxClassNameField;
        
        private CustomerDataGroupExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int taxClassId
        {
            get
            {
                return this.taxClassIdField;
            }
            set
            {
                this.taxClassIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string taxClassName
        {
            get
            {
                return this.taxClassNameField;
            }
            set
            {
                this.taxClassNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public CustomerDataGroupExtensionInterface extensionAttributes
        {
            get
            {
                return this.extensionAttributesField;
            }
            set
            {
                this.extensionAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class CustomerGroupRepositoryV1GetByIdResponse
    {
        
        private CustomerDataGroupInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CustomerDataGroupInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class CustomerGroupRepositoryV1GetByIdRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1", ConfigurationName="Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepo" +
        "sitoryV1.customerGroupRepositoryV1PortType")]
    public interface customerGroupRepositoryV1PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupRepositoryV1GetById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.GenericFault), Action="customerGroupRepositoryV1GetById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetByIdResponse1> customerGroupRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetByIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupRepositoryV1GetList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.GenericFault), Action="customerGroupRepositoryV1GetList", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetListResponse1> customerGroupRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupRepositoryV1Save", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.GenericFault), Action="customerGroupRepositoryV1Save", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1SaveResponse1> customerGroupRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1SaveRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupRepositoryV1DeleteById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.GenericFault), Action="customerGroupRepositoryV1DeleteById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1DeleteByIdResponse1> customerGroupRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1DeleteByIdRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1GetByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
            "ryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1GetByIdRequest customerGroupRepositoryV1GetByIdRequest;
        
        public customerGroupRepositoryV1GetByIdRequest1()
        {
        }
        
        public customerGroupRepositoryV1GetByIdRequest1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1GetByIdRequest customerGroupRepositoryV1GetByIdRequest)
        {
            this.customerGroupRepositoryV1GetByIdRequest = customerGroupRepositoryV1GetByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1GetByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
            "ryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1GetByIdResponse customerGroupRepositoryV1GetByIdResponse;
        
        public customerGroupRepositoryV1GetByIdResponse1()
        {
        }
        
        public customerGroupRepositoryV1GetByIdResponse1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1GetByIdResponse customerGroupRepositoryV1GetByIdResponse)
        {
            this.customerGroupRepositoryV1GetByIdResponse = customerGroupRepositoryV1GetByIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class CustomerGroupRepositoryV1GetListRequest
    {
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FrameworkSearchCriteriaInterface searchCriteria
        {
            get
            {
                return this.searchCriteriaField;
            }
            set
            {
                this.searchCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class FrameworkSearchCriteriaInterface
    {
        
        private FrameworkSearchFilterGroup[] filterGroupsField;
        
        private FrameworkSortOrder[] sortOrdersField;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private int currentPageField;
        
        private bool currentPageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSearchFilterGroup[] filterGroups
        {
            get
            {
                return this.filterGroupsField;
            }
            set
            {
                this.filterGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSortOrder[] sortOrders
        {
            get
            {
                return this.sortOrdersField;
            }
            set
            {
                this.sortOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified
        {
            get
            {
                return this.pageSizeFieldSpecified;
            }
            set
            {
                this.pageSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int currentPage
        {
            get
            {
                return this.currentPageField;
            }
            set
            {
                this.currentPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentPageSpecified
        {
            get
            {
                return this.currentPageFieldSpecified;
            }
            set
            {
                this.currentPageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class FrameworkSearchFilterGroup
    {
        
        private FrameworkFilter[] filtersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkFilter[] filters
        {
            get
            {
                return this.filtersField;
            }
            set
            {
                this.filtersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class FrameworkFilter
    {
        
        private string fieldField;
        
        private string valueField;
        
        private string conditionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string conditionType
        {
            get
            {
                return this.conditionTypeField;
            }
            set
            {
                this.conditionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class FrameworkSortOrder
    {
        
        private string fieldField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class CustomerGroupRepositoryV1GetListResponse
    {
        
        private CustomerDataGroupSearchResultsInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CustomerDataGroupSearchResultsInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class CustomerDataGroupSearchResultsInterface
    {
        
        private CustomerDataGroupInterface[] itemsField;
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        private int totalCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CustomerDataGroupInterface[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public FrameworkSearchCriteriaInterface searchCriteria
        {
            get
            {
                return this.searchCriteriaField;
            }
            set
            {
                this.searchCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int totalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1GetListRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
            "ryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1GetListRequest customerGroupRepositoryV1GetListRequest;
        
        public customerGroupRepositoryV1GetListRequest1()
        {
        }
        
        public customerGroupRepositoryV1GetListRequest1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1GetListRequest customerGroupRepositoryV1GetListRequest)
        {
            this.customerGroupRepositoryV1GetListRequest = customerGroupRepositoryV1GetListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1GetListResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
            "ryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1GetListResponse customerGroupRepositoryV1GetListResponse;
        
        public customerGroupRepositoryV1GetListResponse1()
        {
        }
        
        public customerGroupRepositoryV1GetListResponse1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1GetListResponse customerGroupRepositoryV1GetListResponse)
        {
            this.customerGroupRepositoryV1GetListResponse = customerGroupRepositoryV1GetListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class CustomerGroupRepositoryV1SaveRequest
    {
        
        private CustomerDataGroupInterface groupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CustomerDataGroupInterface group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class CustomerGroupRepositoryV1SaveResponse
    {
        
        private CustomerDataGroupInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CustomerDataGroupInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1SaveRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
            "ryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1SaveRequest customerGroupRepositoryV1SaveRequest;
        
        public customerGroupRepositoryV1SaveRequest1()
        {
        }
        
        public customerGroupRepositoryV1SaveRequest1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1SaveRequest customerGroupRepositoryV1SaveRequest)
        {
            this.customerGroupRepositoryV1SaveRequest = customerGroupRepositoryV1SaveRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1SaveResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
            "ryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1SaveResponse customerGroupRepositoryV1SaveResponse;
        
        public customerGroupRepositoryV1SaveResponse1()
        {
        }
        
        public customerGroupRepositoryV1SaveResponse1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1SaveResponse customerGroupRepositoryV1SaveResponse)
        {
            this.customerGroupRepositoryV1SaveResponse = customerGroupRepositoryV1SaveResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class CustomerGroupRepositoryV1DeleteByIdRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
        "ryV1")]
    public partial class CustomerGroupRepositoryV1DeleteByIdResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1DeleteByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
            "ryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1DeleteByIdRequest customerGroupRepositoryV1DeleteByIdRequest;
        
        public customerGroupRepositoryV1DeleteByIdRequest1()
        {
        }
        
        public customerGroupRepositoryV1DeleteByIdRequest1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1DeleteByIdRequest customerGroupRepositoryV1DeleteByIdRequest)
        {
            this.customerGroupRepositoryV1DeleteByIdRequest = customerGroupRepositoryV1DeleteByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1DeleteByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
            "ryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1DeleteByIdResponse customerGroupRepositoryV1DeleteByIdResponse;
        
        public customerGroupRepositoryV1DeleteByIdResponse1()
        {
        }
        
        public customerGroupRepositoryV1DeleteByIdResponse1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1DeleteByIdResponse customerGroupRepositoryV1DeleteByIdResponse)
        {
            this.customerGroupRepositoryV1DeleteByIdResponse = customerGroupRepositoryV1DeleteByIdResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public interface customerGroupRepositoryV1PortTypeChannel : Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public partial class customerGroupRepositoryV1PortTypeClient : System.ServiceModel.ClientBase<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1PortType>, Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1PortType
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public customerGroupRepositoryV1PortTypeClient() : 
                base(customerGroupRepositoryV1PortTypeClient.GetDefaultBinding(), customerGroupRepositoryV1PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.customerGroupRepositoryV1Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public customerGroupRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(customerGroupRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), customerGroupRepositoryV1PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public customerGroupRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(customerGroupRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public customerGroupRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(customerGroupRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public customerGroupRepositoryV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetByIdResponse1> Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1PortType.customerGroupRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetByIdRequest1 request)
        {
            return base.Channel.customerGroupRepositoryV1GetByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetByIdResponse1> customerGroupRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1GetByIdRequest customerGroupRepositoryV1GetByIdRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetByIdRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetByIdRequest1();
            inValue.customerGroupRepositoryV1GetByIdRequest = customerGroupRepositoryV1GetByIdRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1PortType)(this)).customerGroupRepositoryV1GetByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetListResponse1> Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1PortType.customerGroupRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetListRequest1 request)
        {
            return base.Channel.customerGroupRepositoryV1GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetListResponse1> customerGroupRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1GetListRequest customerGroupRepositoryV1GetListRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetListRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1GetListRequest1();
            inValue.customerGroupRepositoryV1GetListRequest = customerGroupRepositoryV1GetListRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1PortType)(this)).customerGroupRepositoryV1GetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1SaveResponse1> Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1PortType.customerGroupRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1SaveRequest1 request)
        {
            return base.Channel.customerGroupRepositoryV1SaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1SaveResponse1> customerGroupRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1SaveRequest customerGroupRepositoryV1SaveRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1SaveRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1SaveRequest1();
            inValue.customerGroupRepositoryV1SaveRequest = customerGroupRepositoryV1SaveRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1PortType)(this)).customerGroupRepositoryV1SaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1DeleteByIdResponse1> Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1PortType.customerGroupRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1DeleteByIdRequest1 request)
        {
            return base.Channel.customerGroupRepositoryV1DeleteByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1DeleteByIdResponse1> customerGroupRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.CustomerGroupRepositoryV1DeleteByIdRequest customerGroupRepositoryV1DeleteByIdRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1DeleteByIdRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1DeleteByIdRequest1();
            inValue.customerGroupRepositoryV1DeleteByIdRequest = customerGroupRepositoryV1DeleteByIdRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.CustomerGroupRepositoryV1.customerGroupRepositoryV1PortType)(this)).customerGroupRepositoryV1DeleteByIdAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.customerGroupRepositoryV1Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.customerGroupRepositoryV1Port))
            {
                return new System.ServiceModel.EndpointAddress("http://connector.monnier.cidev04.test/soap/default?services=customerGroupReposito" +
                        "ryV1");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return customerGroupRepositoryV1PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.customerGroupRepositoryV1Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return customerGroupRepositoryV1PortTypeClient.GetEndpointAddress(EndpointConfiguration.customerGroupRepositoryV1Port);
        }
        
        public enum EndpointConfiguration
        {
            
            customerGroupRepositoryV1Port,
        }
    }
}
