//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=eavAttributeSetManage" +
        "mentV1")]
    public partial class GenericFault
    {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors
        {
            get
            {
                return this.wrappedErrorsField;
            }
            set
            {
                this.wrappedErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=eavAttributeSetManage" +
        "mentV1")]
    public partial class GenericFaultParameter
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=eavAttributeSetManage" +
        "mentV1")]
    public partial class WrappedError
    {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=eavAttributeSetManage" +
        "mentV1")]
    public partial class EavAttributeSetManagementV1CreateResponse
    {
        
        private EavDataAttributeSetInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public EavDataAttributeSetInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=eavAttributeSetManage" +
        "mentV1")]
    public partial class EavDataAttributeSetInterface
    {
        
        private int attributeSetIdField;
        
        private bool attributeSetIdFieldSpecified;
        
        private string attributeSetNameField;
        
        private int sortOrderField;
        
        private int entityTypeIdField;
        
        private bool entityTypeIdFieldSpecified;
        
        private EavDataAttributeSetExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int attributeSetId
        {
            get
            {
                return this.attributeSetIdField;
            }
            set
            {
                this.attributeSetIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attributeSetIdSpecified
        {
            get
            {
                return this.attributeSetIdFieldSpecified;
            }
            set
            {
                this.attributeSetIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string attributeSetName
        {
            get
            {
                return this.attributeSetNameField;
            }
            set
            {
                this.attributeSetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int sortOrder
        {
            get
            {
                return this.sortOrderField;
            }
            set
            {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int entityTypeId
        {
            get
            {
                return this.entityTypeIdField;
            }
            set
            {
                this.entityTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entityTypeIdSpecified
        {
            get
            {
                return this.entityTypeIdFieldSpecified;
            }
            set
            {
                this.entityTypeIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public EavDataAttributeSetExtensionInterface extensionAttributes
        {
            get
            {
                return this.extensionAttributesField;
            }
            set
            {
                this.extensionAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=eavAttributeSetManage" +
        "mentV1")]
    public partial class EavDataAttributeSetExtensionInterface
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=eavAttributeSetManage" +
        "mentV1")]
    public partial class EavAttributeSetManagementV1CreateRequest
    {
        
        private string entityTypeCodeField;
        
        private EavDataAttributeSetInterface attributeSetField;
        
        private int skeletonIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityTypeCode
        {
            get
            {
                return this.entityTypeCodeField;
            }
            set
            {
                this.entityTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public EavDataAttributeSetInterface attributeSet
        {
            get
            {
                return this.attributeSetField;
            }
            set
            {
                this.attributeSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int skeletonId
        {
            get
            {
                return this.skeletonIdField;
            }
            set
            {
                this.skeletonIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=eavAttributeSetManage" +
        "mentV1", ConfigurationName="Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetMa" +
        "nagementV1.eavAttributeSetManagementV1PortType")]
    public interface eavAttributeSetManagementV1PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="eavAttributeSetManagementV1Create", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.GenericFault), Action="eavAttributeSetManagementV1Create", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.eavAttributeSetManagementV1CreateResponse1> eavAttributeSetManagementV1CreateAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.eavAttributeSetManagementV1CreateRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eavAttributeSetManagementV1CreateRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=eavAttributeSetManage" +
            "mentV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.EavAttributeSetManagementV1CreateRequest eavAttributeSetManagementV1CreateRequest;
        
        public eavAttributeSetManagementV1CreateRequest1()
        {
        }
        
        public eavAttributeSetManagementV1CreateRequest1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.EavAttributeSetManagementV1CreateRequest eavAttributeSetManagementV1CreateRequest)
        {
            this.eavAttributeSetManagementV1CreateRequest = eavAttributeSetManagementV1CreateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eavAttributeSetManagementV1CreateResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=eavAttributeSetManage" +
            "mentV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.EavAttributeSetManagementV1CreateResponse eavAttributeSetManagementV1CreateResponse;
        
        public eavAttributeSetManagementV1CreateResponse1()
        {
        }
        
        public eavAttributeSetManagementV1CreateResponse1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.EavAttributeSetManagementV1CreateResponse eavAttributeSetManagementV1CreateResponse)
        {
            this.eavAttributeSetManagementV1CreateResponse = eavAttributeSetManagementV1CreateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public interface eavAttributeSetManagementV1PortTypeChannel : Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.eavAttributeSetManagementV1PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public partial class eavAttributeSetManagementV1PortTypeClient : System.ServiceModel.ClientBase<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.eavAttributeSetManagementV1PortType>, Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.eavAttributeSetManagementV1PortType
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public eavAttributeSetManagementV1PortTypeClient() : 
                base(eavAttributeSetManagementV1PortTypeClient.GetDefaultBinding(), eavAttributeSetManagementV1PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.eavAttributeSetManagementV1Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public eavAttributeSetManagementV1PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(eavAttributeSetManagementV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), eavAttributeSetManagementV1PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public eavAttributeSetManagementV1PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(eavAttributeSetManagementV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public eavAttributeSetManagementV1PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(eavAttributeSetManagementV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public eavAttributeSetManagementV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.eavAttributeSetManagementV1CreateResponse1> Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.eavAttributeSetManagementV1PortType.eavAttributeSetManagementV1CreateAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.eavAttributeSetManagementV1CreateRequest1 request)
        {
            return base.Channel.eavAttributeSetManagementV1CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.eavAttributeSetManagementV1CreateResponse1> eavAttributeSetManagementV1CreateAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.EavAttributeSetManagementV1CreateRequest eavAttributeSetManagementV1CreateRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.eavAttributeSetManagementV1CreateRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.eavAttributeSetManagementV1CreateRequest1();
            inValue.eavAttributeSetManagementV1CreateRequest = eavAttributeSetManagementV1CreateRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.EavAttributeSetManagementV1.eavAttributeSetManagementV1PortType)(this)).eavAttributeSetManagementV1CreateAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.eavAttributeSetManagementV1Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.eavAttributeSetManagementV1Port))
            {
                return new System.ServiceModel.EndpointAddress("http://connector.monnier.cidev04.test/soap/default?services=eavAttributeSetManage" +
                        "mentV1");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return eavAttributeSetManagementV1PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.eavAttributeSetManagementV1Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return eavAttributeSetManagementV1PortTypeClient.GetEndpointAddress(EndpointConfiguration.eavAttributeSetManagementV1Port);
        }
        
        public enum EndpointConfiguration
        {
            
            eavAttributeSetManagementV1Port,
        }
    }
}
