//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class GenericFault
    {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors
        {
            get
            {
                return this.wrappedErrorsField;
            }
            set
            {
                this.wrappedErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class GenericFaultParameter
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class QuoteGuestCartTotalManagementV1CollectTotalsResponse
    {
        
        private QuoteDataTotalsInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public QuoteDataTotalsInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class QuoteDataTotalsInterface
    {
        
        private float grandTotalField;
        
        private bool grandTotalFieldSpecified;
        
        private float baseGrandTotalField;
        
        private bool baseGrandTotalFieldSpecified;
        
        private float subtotalField;
        
        private bool subtotalFieldSpecified;
        
        private float baseSubtotalField;
        
        private bool baseSubtotalFieldSpecified;
        
        private float discountAmountField;
        
        private bool discountAmountFieldSpecified;
        
        private float baseDiscountAmountField;
        
        private bool baseDiscountAmountFieldSpecified;
        
        private float subtotalWithDiscountField;
        
        private bool subtotalWithDiscountFieldSpecified;
        
        private float baseSubtotalWithDiscountField;
        
        private bool baseSubtotalWithDiscountFieldSpecified;
        
        private float shippingAmountField;
        
        private bool shippingAmountFieldSpecified;
        
        private float baseShippingAmountField;
        
        private bool baseShippingAmountFieldSpecified;
        
        private float shippingDiscountAmountField;
        
        private bool shippingDiscountAmountFieldSpecified;
        
        private float baseShippingDiscountAmountField;
        
        private bool baseShippingDiscountAmountFieldSpecified;
        
        private float taxAmountField;
        
        private bool taxAmountFieldSpecified;
        
        private float baseTaxAmountField;
        
        private bool baseTaxAmountFieldSpecified;
        
        private float weeeTaxAppliedAmountField;
        
        private float shippingTaxAmountField;
        
        private bool shippingTaxAmountFieldSpecified;
        
        private float baseShippingTaxAmountField;
        
        private bool baseShippingTaxAmountFieldSpecified;
        
        private float subtotalInclTaxField;
        
        private bool subtotalInclTaxFieldSpecified;
        
        private float baseSubtotalInclTaxField;
        
        private bool baseSubtotalInclTaxFieldSpecified;
        
        private float shippingInclTaxField;
        
        private bool shippingInclTaxFieldSpecified;
        
        private float baseShippingInclTaxField;
        
        private bool baseShippingInclTaxFieldSpecified;
        
        private string baseCurrencyCodeField;
        
        private string quoteCurrencyCodeField;
        
        private string couponCodeField;
        
        private int itemsQtyField;
        
        private bool itemsQtyFieldSpecified;
        
        private QuoteDataTotalsItemInterface[] itemsField;
        
        private QuoteDataTotalSegmentInterface[] totalSegmentsField;
        
        private QuoteDataTotalsExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public float grandTotal
        {
            get
            {
                return this.grandTotalField;
            }
            set
            {
                this.grandTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grandTotalSpecified
        {
            get
            {
                return this.grandTotalFieldSpecified;
            }
            set
            {
                this.grandTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public float baseGrandTotal
        {
            get
            {
                return this.baseGrandTotalField;
            }
            set
            {
                this.baseGrandTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseGrandTotalSpecified
        {
            get
            {
                return this.baseGrandTotalFieldSpecified;
            }
            set
            {
                this.baseGrandTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public float subtotal
        {
            get
            {
                return this.subtotalField;
            }
            set
            {
                this.subtotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subtotalSpecified
        {
            get
            {
                return this.subtotalFieldSpecified;
            }
            set
            {
                this.subtotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public float baseSubtotal
        {
            get
            {
                return this.baseSubtotalField;
            }
            set
            {
                this.baseSubtotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseSubtotalSpecified
        {
            get
            {
                return this.baseSubtotalFieldSpecified;
            }
            set
            {
                this.baseSubtotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public float discountAmount
        {
            get
            {
                return this.discountAmountField;
            }
            set
            {
                this.discountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountAmountSpecified
        {
            get
            {
                return this.discountAmountFieldSpecified;
            }
            set
            {
                this.discountAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public float baseDiscountAmount
        {
            get
            {
                return this.baseDiscountAmountField;
            }
            set
            {
                this.baseDiscountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseDiscountAmountSpecified
        {
            get
            {
                return this.baseDiscountAmountFieldSpecified;
            }
            set
            {
                this.baseDiscountAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public float subtotalWithDiscount
        {
            get
            {
                return this.subtotalWithDiscountField;
            }
            set
            {
                this.subtotalWithDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subtotalWithDiscountSpecified
        {
            get
            {
                return this.subtotalWithDiscountFieldSpecified;
            }
            set
            {
                this.subtotalWithDiscountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public float baseSubtotalWithDiscount
        {
            get
            {
                return this.baseSubtotalWithDiscountField;
            }
            set
            {
                this.baseSubtotalWithDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseSubtotalWithDiscountSpecified
        {
            get
            {
                return this.baseSubtotalWithDiscountFieldSpecified;
            }
            set
            {
                this.baseSubtotalWithDiscountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public float shippingAmount
        {
            get
            {
                return this.shippingAmountField;
            }
            set
            {
                this.shippingAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shippingAmountSpecified
        {
            get
            {
                return this.shippingAmountFieldSpecified;
            }
            set
            {
                this.shippingAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public float baseShippingAmount
        {
            get
            {
                return this.baseShippingAmountField;
            }
            set
            {
                this.baseShippingAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseShippingAmountSpecified
        {
            get
            {
                return this.baseShippingAmountFieldSpecified;
            }
            set
            {
                this.baseShippingAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public float shippingDiscountAmount
        {
            get
            {
                return this.shippingDiscountAmountField;
            }
            set
            {
                this.shippingDiscountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shippingDiscountAmountSpecified
        {
            get
            {
                return this.shippingDiscountAmountFieldSpecified;
            }
            set
            {
                this.shippingDiscountAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public float baseShippingDiscountAmount
        {
            get
            {
                return this.baseShippingDiscountAmountField;
            }
            set
            {
                this.baseShippingDiscountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseShippingDiscountAmountSpecified
        {
            get
            {
                return this.baseShippingDiscountAmountFieldSpecified;
            }
            set
            {
                this.baseShippingDiscountAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public float taxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxAmountSpecified
        {
            get
            {
                return this.taxAmountFieldSpecified;
            }
            set
            {
                this.taxAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public float baseTaxAmount
        {
            get
            {
                return this.baseTaxAmountField;
            }
            set
            {
                this.baseTaxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseTaxAmountSpecified
        {
            get
            {
                return this.baseTaxAmountFieldSpecified;
            }
            set
            {
                this.baseTaxAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public float weeeTaxAppliedAmount
        {
            get
            {
                return this.weeeTaxAppliedAmountField;
            }
            set
            {
                this.weeeTaxAppliedAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public float shippingTaxAmount
        {
            get
            {
                return this.shippingTaxAmountField;
            }
            set
            {
                this.shippingTaxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shippingTaxAmountSpecified
        {
            get
            {
                return this.shippingTaxAmountFieldSpecified;
            }
            set
            {
                this.shippingTaxAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public float baseShippingTaxAmount
        {
            get
            {
                return this.baseShippingTaxAmountField;
            }
            set
            {
                this.baseShippingTaxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseShippingTaxAmountSpecified
        {
            get
            {
                return this.baseShippingTaxAmountFieldSpecified;
            }
            set
            {
                this.baseShippingTaxAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public float subtotalInclTax
        {
            get
            {
                return this.subtotalInclTaxField;
            }
            set
            {
                this.subtotalInclTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subtotalInclTaxSpecified
        {
            get
            {
                return this.subtotalInclTaxFieldSpecified;
            }
            set
            {
                this.subtotalInclTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public float baseSubtotalInclTax
        {
            get
            {
                return this.baseSubtotalInclTaxField;
            }
            set
            {
                this.baseSubtotalInclTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseSubtotalInclTaxSpecified
        {
            get
            {
                return this.baseSubtotalInclTaxFieldSpecified;
            }
            set
            {
                this.baseSubtotalInclTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public float shippingInclTax
        {
            get
            {
                return this.shippingInclTaxField;
            }
            set
            {
                this.shippingInclTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shippingInclTaxSpecified
        {
            get
            {
                return this.shippingInclTaxFieldSpecified;
            }
            set
            {
                this.shippingInclTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public float baseShippingInclTax
        {
            get
            {
                return this.baseShippingInclTaxField;
            }
            set
            {
                this.baseShippingInclTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseShippingInclTaxSpecified
        {
            get
            {
                return this.baseShippingInclTaxFieldSpecified;
            }
            set
            {
                this.baseShippingInclTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string baseCurrencyCode
        {
            get
            {
                return this.baseCurrencyCodeField;
            }
            set
            {
                this.baseCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string quoteCurrencyCode
        {
            get
            {
                return this.quoteCurrencyCodeField;
            }
            set
            {
                this.quoteCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string couponCode
        {
            get
            {
                return this.couponCodeField;
            }
            set
            {
                this.couponCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public int itemsQty
        {
            get
            {
                return this.itemsQtyField;
            }
            set
            {
                this.itemsQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itemsQtySpecified
        {
            get
            {
                return this.itemsQtyFieldSpecified;
            }
            set
            {
                this.itemsQtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public QuoteDataTotalsItemInterface[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public QuoteDataTotalSegmentInterface[] totalSegments
        {
            get
            {
                return this.totalSegmentsField;
            }
            set
            {
                this.totalSegmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public QuoteDataTotalsExtensionInterface extensionAttributes
        {
            get
            {
                return this.extensionAttributesField;
            }
            set
            {
                this.extensionAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class QuoteDataTotalsItemInterface
    {
        
        private int itemIdField;
        
        private float priceField;
        
        private float basePriceField;
        
        private float qtyField;
        
        private float rowTotalField;
        
        private float baseRowTotalField;
        
        private float rowTotalWithDiscountField;
        
        private bool rowTotalWithDiscountFieldSpecified;
        
        private float taxAmountField;
        
        private bool taxAmountFieldSpecified;
        
        private float baseTaxAmountField;
        
        private bool baseTaxAmountFieldSpecified;
        
        private float taxPercentField;
        
        private bool taxPercentFieldSpecified;
        
        private float discountAmountField;
        
        private bool discountAmountFieldSpecified;
        
        private float baseDiscountAmountField;
        
        private bool baseDiscountAmountFieldSpecified;
        
        private float discountPercentField;
        
        private bool discountPercentFieldSpecified;
        
        private float priceInclTaxField;
        
        private bool priceInclTaxFieldSpecified;
        
        private float basePriceInclTaxField;
        
        private bool basePriceInclTaxFieldSpecified;
        
        private float rowTotalInclTaxField;
        
        private bool rowTotalInclTaxFieldSpecified;
        
        private float baseRowTotalInclTaxField;
        
        private bool baseRowTotalInclTaxFieldSpecified;
        
        private string optionsField;
        
        private float weeeTaxAppliedAmountField;
        
        private string weeeTaxAppliedField;
        
        private QuoteDataTotalsItemExtensionInterface extensionAttributesField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int itemId
        {
            get
            {
                return this.itemIdField;
            }
            set
            {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public float price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public float basePrice
        {
            get
            {
                return this.basePriceField;
            }
            set
            {
                this.basePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public float qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public float rowTotal
        {
            get
            {
                return this.rowTotalField;
            }
            set
            {
                this.rowTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public float baseRowTotal
        {
            get
            {
                return this.baseRowTotalField;
            }
            set
            {
                this.baseRowTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public float rowTotalWithDiscount
        {
            get
            {
                return this.rowTotalWithDiscountField;
            }
            set
            {
                this.rowTotalWithDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rowTotalWithDiscountSpecified
        {
            get
            {
                return this.rowTotalWithDiscountFieldSpecified;
            }
            set
            {
                this.rowTotalWithDiscountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public float taxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxAmountSpecified
        {
            get
            {
                return this.taxAmountFieldSpecified;
            }
            set
            {
                this.taxAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public float baseTaxAmount
        {
            get
            {
                return this.baseTaxAmountField;
            }
            set
            {
                this.baseTaxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseTaxAmountSpecified
        {
            get
            {
                return this.baseTaxAmountFieldSpecified;
            }
            set
            {
                this.baseTaxAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public float taxPercent
        {
            get
            {
                return this.taxPercentField;
            }
            set
            {
                this.taxPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxPercentSpecified
        {
            get
            {
                return this.taxPercentFieldSpecified;
            }
            set
            {
                this.taxPercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public float discountAmount
        {
            get
            {
                return this.discountAmountField;
            }
            set
            {
                this.discountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountAmountSpecified
        {
            get
            {
                return this.discountAmountFieldSpecified;
            }
            set
            {
                this.discountAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public float baseDiscountAmount
        {
            get
            {
                return this.baseDiscountAmountField;
            }
            set
            {
                this.baseDiscountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseDiscountAmountSpecified
        {
            get
            {
                return this.baseDiscountAmountFieldSpecified;
            }
            set
            {
                this.baseDiscountAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public float discountPercent
        {
            get
            {
                return this.discountPercentField;
            }
            set
            {
                this.discountPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountPercentSpecified
        {
            get
            {
                return this.discountPercentFieldSpecified;
            }
            set
            {
                this.discountPercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public float priceInclTax
        {
            get
            {
                return this.priceInclTaxField;
            }
            set
            {
                this.priceInclTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceInclTaxSpecified
        {
            get
            {
                return this.priceInclTaxFieldSpecified;
            }
            set
            {
                this.priceInclTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public float basePriceInclTax
        {
            get
            {
                return this.basePriceInclTaxField;
            }
            set
            {
                this.basePriceInclTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool basePriceInclTaxSpecified
        {
            get
            {
                return this.basePriceInclTaxFieldSpecified;
            }
            set
            {
                this.basePriceInclTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public float rowTotalInclTax
        {
            get
            {
                return this.rowTotalInclTaxField;
            }
            set
            {
                this.rowTotalInclTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rowTotalInclTaxSpecified
        {
            get
            {
                return this.rowTotalInclTaxFieldSpecified;
            }
            set
            {
                this.rowTotalInclTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public float baseRowTotalInclTax
        {
            get
            {
                return this.baseRowTotalInclTaxField;
            }
            set
            {
                this.baseRowTotalInclTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseRowTotalInclTaxSpecified
        {
            get
            {
                return this.baseRowTotalInclTaxFieldSpecified;
            }
            set
            {
                this.baseRowTotalInclTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string options
        {
            get
            {
                return this.optionsField;
            }
            set
            {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public float weeeTaxAppliedAmount
        {
            get
            {
                return this.weeeTaxAppliedAmountField;
            }
            set
            {
                this.weeeTaxAppliedAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string weeeTaxApplied
        {
            get
            {
                return this.weeeTaxAppliedField;
            }
            set
            {
                this.weeeTaxAppliedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public QuoteDataTotalsItemExtensionInterface extensionAttributes
        {
            get
            {
                return this.extensionAttributesField;
            }
            set
            {
                this.extensionAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class QuoteDataTotalsItemExtensionInterface
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class QuoteDataTotalSegmentInterface
    {
        
        private string codeField;
        
        private string titleField;
        
        private float valueField;
        
        private string areaField;
        
        private QuoteDataTotalSegmentExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public float value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public QuoteDataTotalSegmentExtensionInterface extensionAttributes
        {
            get
            {
                return this.extensionAttributesField;
            }
            set
            {
                this.extensionAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class QuoteDataTotalSegmentExtensionInterface
    {
        
        private TaxDataGrandTotalDetailsInterface[] taxGrandtotalDetailsField;
        
        private string[] vertexTaxCalculationMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TaxDataGrandTotalDetailsInterface[] taxGrandtotalDetails
        {
            get
            {
                return this.taxGrandtotalDetailsField;
            }
            set
            {
                this.taxGrandtotalDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] vertexTaxCalculationMessages
        {
            get
            {
                return this.vertexTaxCalculationMessagesField;
            }
            set
            {
                this.vertexTaxCalculationMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class TaxDataGrandTotalDetailsInterface
    {
        
        private float amountField;
        
        private TaxDataGrandTotalRatesInterface[] ratesField;
        
        private int groupIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public float amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TaxDataGrandTotalRatesInterface[] rates
        {
            get
            {
                return this.ratesField;
            }
            set
            {
                this.ratesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int groupId
        {
            get
            {
                return this.groupIdField;
            }
            set
            {
                this.groupIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class TaxDataGrandTotalRatesInterface
    {
        
        private string percentField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string percent
        {
            get
            {
                return this.percentField;
            }
            set
            {
                this.percentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class QuoteDataTotalsExtensionInterface
    {
        
        private string couponLabelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string couponLabel
        {
            get
            {
                return this.couponLabelField;
            }
            set
            {
                this.couponLabelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class CustomerDataAddressInterface
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int customerIdField;
        
        private bool customerIdFieldSpecified;
        
        private CustomerDataRegionInterface regionField;
        
        private int regionIdField;
        
        private bool regionIdFieldSpecified;
        
        private string countryIdField;
        
        private string[] streetField;
        
        private string companyField;
        
        private string telephoneField;
        
        private string faxField;
        
        private string postcodeField;
        
        private string cityField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string middlenameField;
        
        private string prefixField;
        
        private string suffixField;
        
        private string vatIdField;
        
        private bool defaultShippingField;
        
        private bool defaultShippingFieldSpecified;
        
        private bool defaultBillingField;
        
        private bool defaultBillingFieldSpecified;
        
        private CustomerDataAddressExtensionInterface extensionAttributesField;
        
        private FrameworkAttributeInterface[] customAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int customerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool customerIdSpecified
        {
            get
            {
                return this.customerIdFieldSpecified;
            }
            set
            {
                this.customerIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public CustomerDataRegionInterface region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int regionId
        {
            get
            {
                return this.regionIdField;
            }
            set
            {
                this.regionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool regionIdSpecified
        {
            get
            {
                return this.regionIdFieldSpecified;
            }
            set
            {
                this.regionIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string countryId
        {
            get
            {
                return this.countryIdField;
            }
            set
            {
                this.countryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telephone
        {
            get
            {
                return this.telephoneField;
            }
            set
            {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string middlename
        {
            get
            {
                return this.middlenameField;
            }
            set
            {
                this.middlenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string prefix
        {
            get
            {
                return this.prefixField;
            }
            set
            {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string suffix
        {
            get
            {
                return this.suffixField;
            }
            set
            {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string vatId
        {
            get
            {
                return this.vatIdField;
            }
            set
            {
                this.vatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public bool defaultShipping
        {
            get
            {
                return this.defaultShippingField;
            }
            set
            {
                this.defaultShippingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool defaultShippingSpecified
        {
            get
            {
                return this.defaultShippingFieldSpecified;
            }
            set
            {
                this.defaultShippingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public bool defaultBilling
        {
            get
            {
                return this.defaultBillingField;
            }
            set
            {
                this.defaultBillingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool defaultBillingSpecified
        {
            get
            {
                return this.defaultBillingFieldSpecified;
            }
            set
            {
                this.defaultBillingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public CustomerDataAddressExtensionInterface extensionAttributes
        {
            get
            {
                return this.extensionAttributesField;
            }
            set
            {
                this.extensionAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkAttributeInterface[] customAttributes
        {
            get
            {
                return this.customAttributesField;
            }
            set
            {
                this.customAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class CustomerDataRegionInterface
    {
        
        private string regionCodeField;
        
        private string regionField;
        
        private int regionIdField;
        
        private CustomerDataRegionExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string regionCode
        {
            get
            {
                return this.regionCodeField;
            }
            set
            {
                this.regionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int regionId
        {
            get
            {
                return this.regionIdField;
            }
            set
            {
                this.regionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public CustomerDataRegionExtensionInterface extensionAttributes
        {
            get
            {
                return this.extensionAttributesField;
            }
            set
            {
                this.extensionAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class CustomerDataRegionExtensionInterface
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class CustomerDataAddressExtensionInterface
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class FrameworkAttributeInterface
    {
        
        private string attributeCodeField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string attributeCode
        {
            get
            {
                return this.attributeCodeField;
            }
            set
            {
                this.attributeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class FrameworkDataImageContentInterface
    {
        
        private string base64EncodedDataField;
        
        private string typeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string base64EncodedData
        {
            get
            {
                return this.base64EncodedDataField;
            }
            set
            {
                this.base64EncodedDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class WrappedError
    {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class GiftMessageDataMessageExtensionInterface
    {
        
        private string entityIdField;
        
        private string entityTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityId
        {
            get
            {
                return this.entityIdField;
            }
            set
            {
                this.entityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string entityType
        {
            get
            {
                return this.entityTypeField;
            }
            set
            {
                this.entityTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class GiftMessageDataMessageInterface
    {
        
        private int giftMessageIdField;
        
        private bool giftMessageIdFieldSpecified;
        
        private int customerIdField;
        
        private bool customerIdFieldSpecified;
        
        private string senderField;
        
        private string recipientField;
        
        private string messageField;
        
        private GiftMessageDataMessageExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int giftMessageId
        {
            get
            {
                return this.giftMessageIdField;
            }
            set
            {
                this.giftMessageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool giftMessageIdSpecified
        {
            get
            {
                return this.giftMessageIdFieldSpecified;
            }
            set
            {
                this.giftMessageIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int customerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool customerIdSpecified
        {
            get
            {
                return this.customerIdFieldSpecified;
            }
            set
            {
                this.customerIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string recipient
        {
            get
            {
                return this.recipientField;
            }
            set
            {
                this.recipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public GiftMessageDataMessageExtensionInterface extensionAttributes
        {
            get
            {
                return this.extensionAttributesField;
            }
            set
            {
                this.extensionAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class QuoteDataTotalsAdditionalDataExtensionInterface
    {
        
        private GiftMessageDataMessageInterface[] giftMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GiftMessageDataMessageInterface[] giftMessages
        {
            get
            {
                return this.giftMessagesField;
            }
            set
            {
                this.giftMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class QuoteDataTotalsAdditionalDataInterface
    {
        
        private QuoteDataTotalsAdditionalDataExtensionInterface extensionAttributesField;
        
        private FrameworkAttributeInterface[] customAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public QuoteDataTotalsAdditionalDataExtensionInterface extensionAttributes
        {
            get
            {
                return this.extensionAttributesField;
            }
            set
            {
                this.extensionAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkAttributeInterface[] customAttributes
        {
            get
            {
                return this.customAttributesField;
            }
            set
            {
                this.customAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class QuoteDataPaymentExtensionInterface
    {
        
        private string[] agreementIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] agreementIds
        {
            get
            {
                return this.agreementIdsField;
            }
            set
            {
                this.agreementIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class QuoteDataPaymentInterface
    {
        
        private string poNumberField;
        
        private string methodField;
        
        private string[] additionalDataField;
        
        private QuoteDataPaymentExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string poNumber
        {
            get
            {
                return this.poNumberField;
            }
            set
            {
                this.poNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string method
        {
            get
            {
                return this.methodField;
            }
            set
            {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] additionalData
        {
            get
            {
                return this.additionalDataField;
            }
            set
            {
                this.additionalDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public QuoteDataPaymentExtensionInterface extensionAttributes
        {
            get
            {
                return this.extensionAttributesField;
            }
            set
            {
                this.extensionAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1")]
    public partial class QuoteGuestCartTotalManagementV1CollectTotalsRequest
    {
        
        private string cartIdField;
        
        private QuoteDataPaymentInterface paymentMethodField;
        
        private string shippingCarrierCodeField;
        
        private string shippingMethodCodeField;
        
        private QuoteDataTotalsAdditionalDataInterface additionalDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cartId
        {
            get
            {
                return this.cartIdField;
            }
            set
            {
                this.cartIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public QuoteDataPaymentInterface paymentMethod
        {
            get
            {
                return this.paymentMethodField;
            }
            set
            {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string shippingCarrierCode
        {
            get
            {
                return this.shippingCarrierCodeField;
            }
            set
            {
                this.shippingCarrierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string shippingMethodCode
        {
            get
            {
                return this.shippingMethodCodeField;
            }
            set
            {
                this.shippingMethodCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public QuoteDataTotalsAdditionalDataInterface additionalData
        {
            get
            {
                return this.additionalDataField;
            }
            set
            {
                this.additionalDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
        "nagementV1", ConfigurationName="Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTot" +
        "alManagementV1.quoteGuestCartTotalManagementV1PortType")]
    public interface quoteGuestCartTotalManagementV1PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="quoteGuestCartTotalManagementV1CollectTotals", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.GenericFault), Action="quoteGuestCartTotalManagementV1CollectTotals", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomerDataAddressInterface))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FrameworkDataImageContentInterface))]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.quoteGuestCartTotalManagementV1CollectTotalsResponse1> quoteGuestCartTotalManagementV1CollectTotalsAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.quoteGuestCartTotalManagementV1CollectTotalsRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class quoteGuestCartTotalManagementV1CollectTotalsRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
            "nagementV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.QuoteGuestCartTotalManagementV1CollectTotalsRequest quoteGuestCartTotalManagementV1CollectTotalsRequest;
        
        public quoteGuestCartTotalManagementV1CollectTotalsRequest1()
        {
        }
        
        public quoteGuestCartTotalManagementV1CollectTotalsRequest1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.QuoteGuestCartTotalManagementV1CollectTotalsRequest quoteGuestCartTotalManagementV1CollectTotalsRequest)
        {
            this.quoteGuestCartTotalManagementV1CollectTotalsRequest = quoteGuestCartTotalManagementV1CollectTotalsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class quoteGuestCartTotalManagementV1CollectTotalsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
            "nagementV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.QuoteGuestCartTotalManagementV1CollectTotalsResponse quoteGuestCartTotalManagementV1CollectTotalsResponse;
        
        public quoteGuestCartTotalManagementV1CollectTotalsResponse1()
        {
        }
        
        public quoteGuestCartTotalManagementV1CollectTotalsResponse1(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.QuoteGuestCartTotalManagementV1CollectTotalsResponse quoteGuestCartTotalManagementV1CollectTotalsResponse)
        {
            this.quoteGuestCartTotalManagementV1CollectTotalsResponse = quoteGuestCartTotalManagementV1CollectTotalsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public interface quoteGuestCartTotalManagementV1PortTypeChannel : Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.quoteGuestCartTotalManagementV1PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public partial class quoteGuestCartTotalManagementV1PortTypeClient : System.ServiceModel.ClientBase<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.quoteGuestCartTotalManagementV1PortType>, Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.quoteGuestCartTotalManagementV1PortType
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public quoteGuestCartTotalManagementV1PortTypeClient() : 
                base(quoteGuestCartTotalManagementV1PortTypeClient.GetDefaultBinding(), quoteGuestCartTotalManagementV1PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.quoteGuestCartTotalManagementV1Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public quoteGuestCartTotalManagementV1PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(quoteGuestCartTotalManagementV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), quoteGuestCartTotalManagementV1PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public quoteGuestCartTotalManagementV1PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(quoteGuestCartTotalManagementV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public quoteGuestCartTotalManagementV1PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(quoteGuestCartTotalManagementV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public quoteGuestCartTotalManagementV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.quoteGuestCartTotalManagementV1CollectTotalsResponse1> Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.quoteGuestCartTotalManagementV1PortType.quoteGuestCartTotalManagementV1CollectTotalsAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.quoteGuestCartTotalManagementV1CollectTotalsRequest1 request)
        {
            return base.Channel.quoteGuestCartTotalManagementV1CollectTotalsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.quoteGuestCartTotalManagementV1CollectTotalsResponse1> quoteGuestCartTotalManagementV1CollectTotalsAsync(Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.QuoteGuestCartTotalManagementV1CollectTotalsRequest quoteGuestCartTotalManagementV1CollectTotalsRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.quoteGuestCartTotalManagementV1CollectTotalsRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.quoteGuestCartTotalManagementV1CollectTotalsRequest1();
            inValue.quoteGuestCartTotalManagementV1CollectTotalsRequest = quoteGuestCartTotalManagementV1CollectTotalsRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.Core.ResourceModel.QuoteGuestCartTotalManagementV1.quoteGuestCartTotalManagementV1PortType)(this)).quoteGuestCartTotalManagementV1CollectTotalsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.quoteGuestCartTotalManagementV1Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.quoteGuestCartTotalManagementV1Port))
            {
                return new System.ServiceModel.EndpointAddress("http://connector.monnier.cidev04.test/soap/default?services=quoteGuestCartTotalMa" +
                        "nagementV1");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return quoteGuestCartTotalManagementV1PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.quoteGuestCartTotalManagementV1Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return quoteGuestCartTotalManagementV1PortTypeClient.GetEndpointAddress(EndpointConfiguration.quoteGuestCartTotalManagementV1Port);
        }
        
        public enum EndpointConfiguration
        {
            
            quoteGuestCartTotalManagementV1Port,
        }
    }
}
